name: "Run coverage"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements_tests.txt
    - name: Install package
      run: |
        python setup.py install sdist bdist_wheel
        twine check dist/*
    - name: Install and run coverage
      run |
        pip install coverage
        coverage run -m pytest
        coverage report -m
        coverage report
