name: "Run tests"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, macOS-10.15, windows-2019]
        python-version: [3.6, 3.7, 3.8, 3.9]
        pytorch-version: ["1.7.0", "1.8.0", "1.9.0", "1.10.0", "1.11.0"]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install torch==${{ matrix.pytorch-version }}
        pip install numpy>=1.16.4 networkx
        pip install -r requirements_tests.txt
    - name: Install package
      run: |
        python setup.py install sdist bdist_wheel
        twine check dist/*
    - name: Test with pytest
      run: |
        pip install pytest coverage
        coverage run -m pytest tests/ -vv
        coverage report -m